DROP USER IF EXISTS Michael;
CREATE USER Michael WITH ENCRYPTED PASSWORD 'stonebreaker';
DROP DATABASE IF EXISTS todo_app;
CREATE DATABASE todo_app;
GRANT ALL ON DATABASE todo_app TO Michael;
CREATETABLE